
# C:\Users\njiang\NI\projects\3Dprojects\dynamic_roots\parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '4D329D66FA1006157E08BFF1F01962DE'
    
_lr_action_items = {'CURVEDNESS':([32,33,57,],[-21,36,-20,]),'FORK_G_DEPTH':([9,10,],[11,-6,]),'AV_RADIUS':([35,36,40,],[38,-23,-22,]),'LENGTH':([18,19,21,],[-13,22,-12,]),'H_ORDER':([12,13,],[14,-7,]),'NUMBER':([1,11,14,18,22,27,28,34,36,38,41,44,46,49,52,55,],[6,13,16,21,25,30,31,37,40,42,45,48,50,53,56,58,]),'BRANCH_ID':([0,3,4,7,17,20,24,54,55,58,],[1,-3,1,-2,-10,-4,-9,-11,-33,-32,]),',':([37,45,],[41,49,]),'TIP_XYZ':([28,29,31,],[-19,32,-18,]),'(':([32,],[34,]),'N_CHILDREN':([43,44,48,],[46,-27,-26,]),'IS_LONGER_THAN':([46,47,50,],[-29,52,-28,]),'GEOD_DEPTH':([22,23,25,],[-15,27,-14,]),'VOLUME':([15,16,17,20,24,54,55,58,],[18,-8,-10,18,-9,-11,-33,-32,]),'PCA_VERT_ANGLE':([38,39,42,],[-25,44,-24,]),'CLASS_ID':([8,],[10,]),'PCA_PARENT_CHILD_ANGLE':([51,52,56,],[55,-31,-30,]),')':([53,],[57,]),'$end':([2,3,4,7,17,20,24,54,55,58,],[0,-3,-1,-2,-10,-4,-9,-11,-33,-32,]),'CLASS':([5,6,],[8,-5,]),'VERT_DEPTH':([26,27,30,],[28,-17,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'n_children':([43,],[47,]),'file':([0,],[2,]),'curvedness':([33,],[35,]),'timestep':([15,20,],[17,24,]),'geod_depth':([23,],[26,]),'av_radius':([35,],[39,]),'data':([0,],[4,]),'fork_depth':([9,],[12,]),'h_order':([12,],[15,]),'is_longer_than':([47,],[51,]),'length':([19,],[23,]),'branch':([0,4,],[5,5,]),'pca_vert_angle':([39,],[43,]),'pca_parent_child_angle':([51,],[54,]),'volume':([15,20,],[19,19,]),'line':([0,4,],[3,7,]),'vert_depth':([26,],[29,]),'tip_xyz':([29,],[33,]),'timesteps':([15,],[20,]),'class':([5,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> file","S'",1,None,None,None),
  ('file -> data','file',1,'p_file_expr','DynamicRootsParser.py',56),
  ('data -> data line','data',2,'p_data_expr','DynamicRootsParser.py',60),
  ('data -> line','data',1,'p_data_expr','DynamicRootsParser.py',61),
  ('line -> branch class fork_depth h_order timesteps','line',5,'p_line_expr','DynamicRootsParser.py',72),
  ('branch -> BRANCH_ID NUMBER','branch',2,'p_branch_id_expr','DynamicRootsParser.py',76),
  ('class -> CLASS CLASS_ID','class',2,'p_class_expr','DynamicRootsParser.py',80),
  ('fork_depth -> FORK_G_DEPTH NUMBER','fork_depth',2,'p_fork_depth_expr','DynamicRootsParser.py',84),
  ('h_order -> H_ORDER NUMBER','h_order',2,'p_h_order_expr','DynamicRootsParser.py',88),
  ('timesteps -> timesteps timestep','timesteps',2,'p_timesteps_expr','DynamicRootsParser.py',92),
  ('timesteps -> timestep','timesteps',1,'p_timesteps_expr','DynamicRootsParser.py',93),
  ('timestep -> volume length geod_depth vert_depth tip_xyz curvedness av_radius pca_vert_angle n_children is_longer_than pca_parent_child_angle','timestep',11,'p_timestep_expr','DynamicRootsParser.py',105),
  ('volume -> VOLUME NUMBER','volume',2,'p_volume_expr','DynamicRootsParser.py',109),
  ('volume -> VOLUME','volume',1,'p_volume_expr','DynamicRootsParser.py',110),
  ('length -> LENGTH NUMBER','length',2,'p_length_expr','DynamicRootsParser.py',117),
  ('length -> LENGTH','length',1,'p_length_expr','DynamicRootsParser.py',118),
  ('geod_depth -> GEOD_DEPTH NUMBER','geod_depth',2,'p_geod_depth_expr','DynamicRootsParser.py',125),
  ('geod_depth -> GEOD_DEPTH','geod_depth',1,'p_geod_depth_expr','DynamicRootsParser.py',126),
  ('vert_depth -> VERT_DEPTH NUMBER','vert_depth',2,'p_vert_depth_expr','DynamicRootsParser.py',133),
  ('vert_depth -> VERT_DEPTH','vert_depth',1,'p_vert_depth_expr','DynamicRootsParser.py',134),
  ('tip_xyz -> TIP_XYZ ( NUMBER , NUMBER , NUMBER )','tip_xyz',8,'p_tip_xyz_expr','DynamicRootsParser.py',142),
  ('tip_xyz -> TIP_XYZ','tip_xyz',1,'p_tip_xyz_expr','DynamicRootsParser.py',143),
  ('curvedness -> CURVEDNESS NUMBER','curvedness',2,'p_curvedness_expr','DynamicRootsParser.py',153),
  ('curvedness -> CURVEDNESS','curvedness',1,'p_curvedness_expr','DynamicRootsParser.py',154),
  ('av_radius -> AV_RADIUS NUMBER','av_radius',2,'p_av_radius_expr','DynamicRootsParser.py',161),
  ('av_radius -> AV_RADIUS','av_radius',1,'p_av_radius_expr','DynamicRootsParser.py',162),
  ('pca_vert_angle -> PCA_VERT_ANGLE NUMBER','pca_vert_angle',2,'p_pca_vert_angle_expr','DynamicRootsParser.py',169),
  ('pca_vert_angle -> PCA_VERT_ANGLE','pca_vert_angle',1,'p_pca_vert_angle_expr','DynamicRootsParser.py',170),
  ('n_children -> N_CHILDREN NUMBER','n_children',2,'p_n_children_expr','DynamicRootsParser.py',177),
  ('n_children -> N_CHILDREN','n_children',1,'p_n_children_expr','DynamicRootsParser.py',178),
  ('is_longer_than -> IS_LONGER_THAN NUMBER','is_longer_than',2,'p_is_longer_than_expr','DynamicRootsParser.py',185),
  ('is_longer_than -> IS_LONGER_THAN','is_longer_than',1,'p_is_longer_than_expr','DynamicRootsParser.py',186),
  ('pca_parent_child_angle -> PCA_PARENT_CHILD_ANGLE NUMBER','pca_parent_child_angle',2,'p_pca_parent_child_angle_expr','DynamicRootsParser.py',193),
  ('pca_parent_child_angle -> PCA_PARENT_CHILD_ANGLE','pca_parent_child_angle',1,'p_pca_parent_child_angle_expr','DynamicRootsParser.py',194),
]
